### PR TITLE
Disk struct

### PR DESCRIPTION
**Pull request by cocotton**
Add a new _Disk_ structure that is used by the _Node_ struct to define its OSDisk and DataDisks.

**Master node**
- 1 OSDisk 
- 2 DataDisks (DockerDisk + EtcdDisk)

**Worker nodes**: 
- 1 OSDisk 
- 1 DataDisk (DockerDisk)

I use OSDisk and DataDisks because that's the way disks [are defined on an Azure Virtual Machine](https://docs.microsoft.com/en-us/azure/templates/microsoft.compute/virtualmachines#template-format).

I also set the osDisk size to 0. This is because I want Azure to determine the osDisk size itself (which it does). Otherwise, if the size provided happens to be smaller than what's define in the Azure Image, Azure will return an error after trying to shrink the disk past its minimum size.

### CODE REVIEW

**Review by r7vme — APPROVED** [review]
LGTM

**Comment by kopiczko** [comment]
I'd say we should only keep lines that are removed. We don't want to expose disk sizes or types. Let's hide it from the interface as long as it isn't needed.

**Comment by cocotton** [comment]
@kopiczko I updated the PR to match the new logic in the [azure-operator PR](https://github.com/giantswarm/azure-operator/pull/71).

**Comment by kopiczko** [comment]
@Cocotton nice, thanks! I think that one can be closed now.

**Pull request merged**
